version: "3.9"  # optional since v1.27.0
services:
  postgis:
    image: postgis/postgis:14-3.3-bullseye #shp2pgsql is not working
    ports:
      - "5432:5432"
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/
      - ./dbdata:/var/lib/postgresql/data
      - ./gisdata:/gisdata
    environment:
      POSTGRES_USER : "postgres"
      POSTGRES_PASSWORD : "1234qwer"
      POSTGRES_DB : "postgres"
      POSTGRESQL_DIR : "./dbdata"
